import { getOwnerPropertyCollections, isPropertyActionRequired, isRejectedProperty, primaryPropertyAction } from './ownerProperties';
import type { Property } from '../types';
const assert=(ok:boolean,message:string)=>{if(!ok)throw new Error(message)};
const p=(status:Property['status'],verificationStatus:Property['verificationStatus']='UNVERIFIED')=>({id:`${status}-${verificationStatus}`,status,verificationStatus,updatedAt:'2026-08-24',images:[],title:status} as unknown as Property);
const rejected=p('DRAFT','REJECTED');
const draft=p('DRAFT');
const all=[p('PUBLISHED'),p('PENDING_REVIEW'),draft,rejected,p('PAUSED'),p('SUSPENDED'),p('ARCHIVED')];
assert(isRejectedProperty(rejected),'composite rejected predicate');
assert(!isRejectedProperty(draft),'ordinary draft is not rejected');
assert(isPropertyActionRequired(draft),'draft action');
assert(isPropertyActionRequired(rejected),'rejected draft action');
assert(!isPropertyActionRequired(p('PENDING_REVIEW')),'review passive');
assert(getOwnerPropertyCollections(all,'action').map(x=>x.verificationStatus).join(',')==='REJECTED,UNVERIFIED','rejected draft retains action priority');
assert(getOwnerPropertyCollections(all,'drafts').length===1,'ordinary drafts exclude rejected drafts');
assert(getOwnerPropertyCollections(all,'review').length===1,'review filter');
assert(getOwnerPropertyCollections(all,'other').length===3,'other filter');
assert(primaryPropertyAction(rejected)==='مراجعة التعديلات','rejected CTA');
assert(primaryPropertyAction(draft)==='استكمال الوحدة','draft CTA');
console.log('OWNER-PROPERTIES-01 derivations passed.');
