import React, { useMemo, useState } from 'react';
import { AlertCircle, CalendarDays, ChevronLeft, CircleUserRound, MapPin, MessageSquare, ReceiptText, Users } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import type { Booking, BookingStatus } from '../../types';
import { Button } from '../ui/Button';
import { BottomSheet } from '../ui/BottomSheet';
import { formatArabicDateRange } from '../../utils/dateFormatter';
import { formatOwnerBookingMoney, getOwnerBookingCollections, getRemainingBalanceMethodLabel, isOwnerBookingChatEligible, ownerBookingStatusPresentation, runOwnerBookingAction } from '../../utils/ownerBookings';

type ConfirmState = { isOpen: boolean; booking: Booking | null; action: 'approve' | 'reject' };
type CancellationConfirmState = { isOpen: boolean; booking: Booking | null; requestId: string | null; action: 'approve' | 'reject'; reason: string };
const resetConfirm: ConfirmState = { isOpen: false, booking: null, action: 'approve' };
const resetCancellationConfirm: CancellationConfirmState = { isOpen: false, booking: null, requestId: null, action: 'approve', reason: '' };

const statusToneClasses = { attention: 'border-amber-200 bg-amber-50 text-amber-900', info: 'border-blue-200 bg-blue-50 text-blue-800', success: 'border-emerald-200 bg-emerald-50 text-emerald-800', quiet: 'border-slate-200 bg-slate-50 text-slate-600', danger: 'border-rose-200 bg-rose-50 text-rose-800' };

const BookingStatusPill: React.FC<{ status: BookingStatus }> = ({ status }) => {
  const presentation = ownerBookingStatusPresentation[status] || { label: 'حالة الحجز', tone: 'quiet' as const };
  return <span className={`inline-flex min-h-7 items-center rounded-full border px-2.5 text-[12px] font-bold ${statusToneClasses[presentation.tone]}`}>{presentation.label}</span>;
};

const GuestAvatar: React.FC<{ name?: string }> = ({ name }) => {
  const initial = name?.trim().charAt(0);
  return <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[var(--konfrm-color-primary-soft)] text-[var(--konfrm-color-primary)]">{initial ? <span className="text-[16px] font-extrabold">{initial}</span> : <CircleUserRound className="h-5 w-5" />}</div>;
};

const PropertyMedia: React.FC<{ booking: Booking }> = ({ booking }) => booking.propertyImage ? <img src={booking.propertyImage} alt={booking.propertyTitle || 'الوحدة'} className="h-16 w-16 shrink-0 rounded-[var(--konfrm-radius-control)] object-cover" /> : <div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-[var(--konfrm-radius-control)] bg-[var(--konfrm-surface-secondary)] text-[var(--konfrm-text-muted)]"><MapPin className="h-5 w-5" /></div>;

const StayFacts: React.FC<{ booking: Booking; compact?: boolean }> = ({ booking, compact = false }) => compact ? <div className="space-y-1.5 text-[13px] text-[var(--konfrm-text-secondary)]"><span className="flex items-center gap-1.5"><CalendarDays className="h-4 w-4 shrink-0 text-[var(--konfrm-color-primary)]" />{formatArabicDateRange(booking.checkIn, booking.checkOut)}</span><span className="flex items-center gap-3"><span>{booking.nights} {booking.nights === 1 ? 'ليلة' : 'ليالٍ'}</span><span className="inline-flex items-center gap-1"><Users className="h-4 w-4 text-[var(--konfrm-text-muted)]" />{booking.guestsCount} {booking.guestsCount === 1 ? 'ضيف' : 'ضيوف'}</span></span></div> : <div className="grid grid-cols-2 gap-2"><div className="rounded-[var(--konfrm-radius-control)] bg-[var(--konfrm-surface-secondary)] p-3"><CalendarDays className="h-4 w-4 text-[var(--konfrm-color-primary)]" /><span className="mt-1 block text-[12px] leading-5 text-[var(--konfrm-text-secondary)]">{formatArabicDateRange(booking.checkIn, booking.checkOut)}</span></div><div className="rounded-[var(--konfrm-radius-control)] bg-[var(--konfrm-surface-secondary)] p-3"><span className="text-[12px] text-[var(--konfrm-text-secondary)]">{booking.nights} {booking.nights === 1 ? 'ليلة' : 'ليالٍ'}</span><span className="mt-2 flex items-center gap-1 text-[13px] text-[var(--konfrm-text-secondary)]"><Users className="h-4 w-4 text-[var(--konfrm-text-muted)]" />{booking.guestsCount} {booking.guestsCount === 1 ? 'ضيف' : 'ضيوف'}</span></div></div>;

const FinancialPreview: React.FC<{ booking: Booking }> = ({ booking }) => {
  const summary = booking.financialSummary;
  if (!summary) return null;
  return <div className="grid grid-cols-2 gap-2 rounded-[var(--konfrm-radius-card)] bg-[var(--konfrm-surface-secondary)] p-3"><div><p className="text-[12px] text-[var(--konfrm-text-secondary)]">إجمالي الحجز</p><p className="mt-1 text-[15px] font-extrabold text-[var(--konfrm-text-primary)]">{formatOwnerBookingMoney(summary.totalBookingValue, summary.currency)}</p></div><div className="border-r border-[var(--konfrm-border-subtle)] pr-3"><p className="text-[12px] text-[var(--konfrm-text-secondary)]">العربون</p><p className="mt-1 text-[15px] font-extrabold text-[var(--konfrm-text-primary)]">{formatOwnerBookingMoney(summary.depositAmount, summary.currency)}</p></div></div>;
};

const BookingDetails: React.FC<{ booking: Booking; cancellationReason?: string; hasPendingCancellation: boolean; onChat: () => void; onApprove: () => void; onReject: () => void; onApproveCancellation: () => void; onRejectCancellation: () => void }> = ({ booking, cancellationReason, hasPendingCancellation, onChat, onApprove, onReject, onApproveCancellation, onRejectCancellation }) => {
  const summary = booking.financialSummary;
  const isPendingRequest = booking.status === 'PENDING_OWNER_APPROVAL';
  const paymentMethod = summary ? getRemainingBalanceMethodLabel(summary.remainingBalancePaymentMethod) : null;
  return <div className="space-y-5 text-right" dir="rtl">
    <div className="flex items-center justify-between rounded-[var(--konfrm-radius-card)] bg-[var(--konfrm-surface-secondary)] p-3"><span className="text-[13px] font-bold text-[var(--konfrm-text-secondary)]">{isPendingRequest ? 'طلب حجز' : 'حالة الحجز'}</span><BookingStatusPill status={booking.status} /></div>
    {booking.status === 'APPROVED_PENDING_PAYMENT' && <div className="rounded-[var(--konfrm-radius-card)] border border-blue-200 bg-blue-50 p-3 text-[13px] leading-6 text-blue-900">وافقت على الطلب. سيتم تأكيد الحجز بعد إتمام خطوة الدفع المطلوبة.</div>}
    <section><p className="mb-2 text-[13px] font-bold text-[var(--konfrm-text-secondary)]">الضيف</p><div className="flex items-center gap-3 rounded-[var(--konfrm-radius-card)] border border-[var(--konfrm-border-default)] bg-[var(--konfrm-surface-primary)] p-3"><GuestAvatar name={booking.renter?.name} /><div className="min-w-0"><h4 className="truncate text-[16px] font-extrabold text-[var(--konfrm-text-primary)]">{booking.renter?.name || 'ضيف'}</h4><p className="mt-1 text-[13px] text-[var(--konfrm-text-secondary)]">التواصل داخل التطبيق فقط</p></div>{isOwnerBookingChatEligible(booking.status) && <button type="button" onClick={onChat} className="mr-auto inline-flex min-h-11 items-center gap-1.5 rounded-[var(--konfrm-radius-control)] px-2 text-[13px] font-bold text-[var(--konfrm-color-primary)]"><MessageSquare className="h-4 w-4" />محادثة</button>}</div></section>
    <section><p className="mb-2 text-[13px] font-bold text-[var(--konfrm-text-secondary)]">الوحدة والإقامة</p><div className="rounded-[var(--konfrm-radius-card)] border border-[var(--konfrm-border-default)] bg-[var(--konfrm-surface-primary)] p-3"><div className="flex gap-3"><PropertyMedia booking={booking} /><div className="min-w-0"><h4 className="truncate text-[15px] font-extrabold text-[var(--konfrm-text-primary)]">{booking.propertyTitle || 'وحدة غير متاحة التفاصيل'}</h4><p className="mt-1 flex items-center gap-1 text-[13px] text-[var(--konfrm-text-secondary)]"><MapPin className="h-4 w-4 shrink-0" /><span className="truncate">{booking.locationName || 'الموقع غير متاح'}</span></p></div></div><div className="mt-3"><StayFacts booking={booking} /></div></div></section>
    {summary && <section><p className="mb-2 text-[13px] font-bold text-[var(--konfrm-text-secondary)]">الملخص المالي</p><div className="divide-y divide-[var(--konfrm-border-subtle)] rounded-[var(--konfrm-radius-card)] border border-[var(--konfrm-border-default)] bg-[var(--konfrm-surface-primary)] px-3">{[['إجمالي الحجز', formatOwnerBookingMoney(summary.totalBookingValue, summary.currency)], ['العربون', formatOwnerBookingMoney(summary.depositAmount, summary.currency)], ['عمولة KONFRM', `-${formatOwnerBookingMoney(summary.solaCommissionAmount, summary.currency)}`], ['صافي العربون للمالك', formatOwnerBookingMoney(summary.ownerNetDepositAmount, summary.currency)], ['المبلغ المتبقي', formatOwnerBookingMoney(summary.remainingBalance, summary.currency)]].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-4 py-3 text-[14px]"><span className="text-[var(--konfrm-text-secondary)]">{label}</span><span className="shrink-0 font-extrabold text-[var(--konfrm-text-primary)]">{value}</span></div>)}{paymentMethod && <div className="flex items-start justify-between gap-4 py-3 text-[14px]"><span className="text-[var(--konfrm-text-secondary)]">طريقة دفع المتبقي</span><span className="max-w-[55%] text-left font-bold text-[var(--konfrm-text-primary)]">{paymentMethod}</span></div>}</div></section>}
    {hasPendingCancellation && <section className="rounded-[var(--konfrm-radius-card)] border border-amber-200 bg-amber-50 p-4"><div className="flex items-center gap-2 text-[15px] font-extrabold text-amber-950"><AlertCircle className="h-5 w-5" />طلب إلغاء يحتاج مراجعة</div><p className="mt-2 text-[13px] leading-6 text-amber-900">{cancellationReason || 'لم يذكر المستأجر سببًا.'}</p><div className="mt-3 grid grid-cols-2 gap-3"><Button variant="primary" size="md" fullWidth onClick={onApproveCancellation}>قبول الإلغاء</Button><Button variant="danger" size="md" fullWidth onClick={onRejectCancellation}>رفض الإلغاء</Button></div></section>}
    {isPendingRequest && <div className="grid grid-cols-2 gap-3 border-t border-[var(--konfrm-border-subtle)] pt-4"><Button variant="primary" size="md" fullWidth onClick={onApprove}>قبول الطلب</Button><Button variant="danger" size="md" fullWidth onClick={onReject}>رفض الطلب</Button></div>}
  </div>;
};

export const BookingsFoundationView: React.FC = () => {
  const { bookings, cancellationRequests, bookingTabSegment, setBookingTabSegment, approveBooking, rejectBooking, approveCancellationRequest, rejectCancellationRequest, openChatForBooking } = useApp();
  const [selectedBooking, setSelectedBooking] = useState<Booking | null>(null);
  const [isDetailsOpen, setIsDetailsOpen] = useState(false);
  const [confirmModal, setConfirmModal] = useState<ConfirmState>(resetConfirm);
  const [cancellationConfirmModal, setCancellationConfirmModal] = useState<CancellationConfirmState>(resetCancellationConfirm);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const collections = useMemo(() => getOwnerBookingCollections(bookings || []), [bookings]);
  const openDetails = (booking: Booking) => { setActionError(null); setSelectedBooking(booking); setIsDetailsOpen(true); };
  const closeDetails = () => { setActionError(null); setIsDetailsOpen(false); };
  const openConfirm = (booking: Booking, action: 'approve' | 'reject') => { setActionError(null); setConfirmModal({ isOpen: true, booking, action }); };
  const getCancellation = (booking: Booking) => cancellationRequests.find((request) => request.bookingId === booking.id && request.status === 'PENDING_REVIEW');
  const openCancellationConfirm = (booking: Booking, action: 'approve' | 'reject') => { const request = getCancellation(booking); setActionError(null); setCancellationConfirmModal({ isOpen: true, booking, requestId: request?.id || booking.activeCancellationRequestId || null, action, reason: '' }); };
  const executeBookingAction = async () => { if (!confirmModal.booking || isSubmitting) return; setIsSubmitting(true); setActionError(null); const outcome = await runOwnerBookingAction(() => confirmModal.action === 'approve' ? approveBooking(confirmModal.booking!.id) : rejectBooking(confirmModal.booking!.id)); setIsSubmitting(false); if (!outcome.ok) { setActionError(outcome.message); return; } setConfirmModal(resetConfirm); closeDetails(); };
  const executeCancellationAction = async () => { if (!cancellationConfirmModal.requestId || isSubmitting) return; setIsSubmitting(true); setActionError(null); const outcome = await runOwnerBookingAction(() => cancellationConfirmModal.action === 'approve' ? approveCancellationRequest(cancellationConfirmModal.requestId!) : rejectCancellationRequest(cancellationConfirmModal.requestId!, cancellationConfirmModal.reason)); setIsSubmitting(false); if (!outcome.ok) { setActionError(outcome.message); return; } setCancellationConfirmModal(resetCancellationConfirm); closeDetails(); };
  const renderBookingCard = (booking: Booking, variant: 'request' | 'active' | 'history') => {
    const pendingCancellation = Boolean(getCancellation(booking) || booking.status === 'CANCELLATION_REQUESTED');
    const isRequest = variant === 'request';
    return <article key={booking.id} className="rounded-[var(--konfrm-radius-elevated-card)] border border-[var(--konfrm-border-default)] bg-[var(--konfrm-surface-primary)] p-4 [box-shadow:var(--konfrm-shadow-subtle)]"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><GuestAvatar name={booking.renter?.name} /><div className="min-w-0"><p className="text-[12px] font-bold text-[var(--konfrm-text-secondary)]">{isRequest ? 'طلب حجز' : booking.renter?.name ? 'الضيف' : 'الحجز'}</p><h3 className="truncate text-[16px] font-extrabold text-[var(--konfrm-text-primary)]">{booking.renter?.name || 'ضيف'}</h3></div></div><BookingStatusPill status={pendingCancellation ? 'CANCELLATION_REQUESTED' : booking.status} /></div><div className="mt-4 flex gap-3"><PropertyMedia booking={booking} /><div className="min-w-0 flex-1"><h4 className="truncate text-[15px] font-extrabold text-[var(--konfrm-text-primary)]">{booking.propertyTitle || 'وحدة غير متاحة التفاصيل'}</h4><p className="mt-1 flex items-center gap-1 text-[13px] text-[var(--konfrm-text-secondary)]"><MapPin className="h-4 w-4 shrink-0" /><span className="truncate">{booking.locationName || 'الموقع غير متاح'}</span></p><div className="mt-2"><StayFacts booking={booking} compact /></div></div></div>{isRequest && <div className="mt-4"><FinancialPreview booking={booking} /></div>}{booking.status === 'APPROVED_PENDING_PAYMENT' && <p className="mt-4 rounded-[var(--konfrm-radius-control)] bg-blue-50 px-3 py-2.5 text-[13px] leading-6 text-blue-900">وافقت على الطلب. سيتم تأكيد الحجز بعد إتمام خطوة الدفع المطلوبة.</p>}{pendingCancellation && <button type="button" onClick={() => openDetails(booking)} className="mt-4 flex min-h-11 items-center gap-2 text-[14px] font-bold text-amber-900"><AlertCircle className="h-4 w-4" />مراجعة طلب الإلغاء</button>}<div className="mt-4 border-t border-[var(--konfrm-border-subtle)] pt-3">{isRequest ? <Button variant="primary" size="md" fullWidth onClick={() => openDetails(booking)}>مراجعة الطلب<ChevronLeft className="h-4 w-4" /></Button> : <div className="flex items-center justify-between gap-3"><button type="button" onClick={() => openDetails(booking)} className="min-h-11 text-[14px] font-bold text-[var(--konfrm-color-primary)]">عرض التفاصيل</button>{isOwnerBookingChatEligible(booking.status) && <button type="button" onClick={() => void openChatForBooking(booking.id)} className="inline-flex min-h-11 items-center gap-1.5 text-[14px] font-bold text-[var(--konfrm-color-primary)]"><MessageSquare className="h-4 w-4" />محادثة المستأجر</button>}</div>}</div></article>;
  };
  const segments: Array<{ id: 'pending' | 'upcoming' | 'past'; label: string; count: number }> = [{ id: 'pending', label: 'الطلبات', count: collections.requests.length }, { id: 'upcoming', label: 'الحجوزات', count: collections.active.length }, { id: 'past', label: 'السجل', count: collections.history.length }];
  const selectedList = bookingTabSegment === 'pending' ? collections.requests : bookingTabSegment === 'upcoming' ? collections.active : collections.history;
  const empty = bookingTabSegment === 'pending' ? ['لا توجد طلبات تحتاج قرارك الآن.', 'عند وصول طلب جديد ستتمكن من مراجعته من هنا.'] : bookingTabSegment === 'upcoming' ? ['لا توجد حجوزات حالية أو قادمة.', 'ستظهر الحجوزات التي تنتظر الدفع أو المؤكدة هنا.'] : ['لا يوجد سجل حجوزات حتى الآن.', 'ستظهر هنا الطلبات المنتهية والملغاة والحجوزات السابقة.'];
  return <main className="min-h-full w-full bg-[var(--konfrm-surface-canvas)] pb-28 text-right" dir="rtl"><div className="mx-auto w-full max-w-[430px] px-[var(--konfrm-space-page-horizontal)] py-5"><header><h1 className="text-[24px] font-extrabold tracking-[-0.01em] text-[var(--konfrm-text-primary)]">الحجوزات</h1><p className="mt-1 text-[14px] leading-6 text-[var(--konfrm-text-secondary)]">راجع الطلبات وتابع حجوزاتك القادمة.</p></header><nav className="mt-5 grid grid-cols-3 rounded-[var(--konfrm-radius-card)] bg-[var(--konfrm-surface-secondary)] p-1.5" aria-label="أقسام الحجوزات">{segments.map((segment) => <button key={segment.id} type="button" onClick={() => setBookingTabSegment(segment.id)} aria-pressed={bookingTabSegment === segment.id} className={`flex min-h-11 items-center justify-center gap-1.5 rounded-[var(--konfrm-radius-control)] px-2 text-[14px] font-bold transition-colors ${bookingTabSegment === segment.id ? 'bg-[var(--konfrm-surface-primary)] text-[var(--konfrm-color-primary)] [box-shadow:var(--konfrm-shadow-subtle)]' : 'text-[var(--konfrm-text-secondary)]'}`}><span>{segment.label}</span>{segment.count > 0 && <span className={`inline-flex min-w-5 items-center justify-center rounded-full px-1.5 py-0.5 text-[12px] ${bookingTabSegment === segment.id ? 'bg-[var(--konfrm-color-primary-soft)]' : 'bg-[var(--konfrm-border-subtle)] text-[var(--konfrm-text-secondary)]'}`}>{segment.count.toLocaleString('ar-EG')}</span>}</button>)}</nav><section className="mt-5 space-y-3" aria-live="polite">{selectedList.length ? selectedList.map((booking) => renderBookingCard(booking, bookingTabSegment === 'pending' ? 'request' : bookingTabSegment === 'upcoming' ? 'active' : 'history')) : <div className="flex min-h-56 flex-col items-center justify-center rounded-[var(--konfrm-radius-elevated-card)] border border-dashed border-[var(--konfrm-border-default)] bg-[var(--konfrm-surface-primary)] px-6 text-center"><ReceiptText className="h-7 w-7 text-[var(--konfrm-text-muted)]" /><h2 className="mt-3 text-[17px] font-extrabold text-[var(--konfrm-text-primary)]">{empty[0]}</h2><p className="mt-2 max-w-[270px] text-[14px] leading-6 text-[var(--konfrm-text-secondary)]">{empty[1]}</p></div>}</section></div>
    <BottomSheet isOpen={isDetailsOpen} onClose={closeDetails} title={selectedBooking?.status === 'PENDING_OWNER_APPROVAL' ? 'تفاصيل طلب الحجز' : 'تفاصيل الحجز'}>{selectedBooking && <BookingDetails booking={selectedBooking} cancellationReason={getCancellation(selectedBooking)?.reason} hasPendingCancellation={Boolean(getCancellation(selectedBooking) || selectedBooking.status === 'CANCELLATION_REQUESTED')} onChat={() => { closeDetails(); void openChatForBooking(selectedBooking.id); }} onApprove={() => openConfirm(selectedBooking, 'approve')} onReject={() => openConfirm(selectedBooking, 'reject')} onApproveCancellation={() => openCancellationConfirm(selectedBooking, 'approve')} onRejectCancellation={() => openCancellationConfirm(selectedBooking, 'reject')} />}</BottomSheet>
    <BottomSheet isOpen={confirmModal.isOpen} onClose={() => !isSubmitting && setConfirmModal(resetConfirm)} title={confirmModal.action === 'approve' ? 'تأكيد قبول الطلب' : 'تأكيد رفض الطلب'}><div className="space-y-5 text-right" dir="rtl"><div className="rounded-[var(--konfrm-radius-card)] bg-[var(--konfrm-surface-secondary)] p-4"><p className="text-[16px] font-extrabold text-[var(--konfrm-text-primary)]">{confirmModal.action === 'approve' ? 'هل تريد قبول هذا الطلب؟' : 'هل تريد رفض هذا الطلب؟'}</p><p className="mt-2 text-[14px] leading-6 text-[var(--konfrm-text-secondary)]">{confirmModal.action === 'approve' ? 'بعد الموافقة سيتمكن المستأجر من إتمام خطوة دفع العربون المطلوبة، ويصبح الحجز مؤكداً بعد نجاح الدفع.' : 'سيتم رفض الطلب وإبلاغ المستأجر، ولن يتحول إلى حجز مؤكد.'}</p></div>{actionError && <p role="alert" className="rounded-[var(--konfrm-radius-control)] border border-rose-200 bg-rose-50 p-3 text-[14px] font-bold text-rose-800">{actionError}</p>}<div className="grid grid-cols-2 gap-3"><Button variant="outline" size="md" fullWidth disabled={isSubmitting} onClick={() => setConfirmModal(resetConfirm)}>إلغاء</Button><Button variant={confirmModal.action === 'approve' ? 'primary' : 'danger'} size="md" fullWidth isLoading={isSubmitting} onClick={() => void executeBookingAction()}>{confirmModal.action === 'approve' ? 'تأكيد القبول' : 'تأكيد الرفض'}</Button></div></div></BottomSheet>
    <BottomSheet isOpen={cancellationConfirmModal.isOpen} onClose={() => !isSubmitting && setCancellationConfirmModal(resetCancellationConfirm)} title={cancellationConfirmModal.action === 'approve' ? 'تأكيد قبول الإلغاء' : 'تأكيد رفض الإلغاء'}><div className="space-y-5 text-right" dir="rtl"><div className="rounded-[var(--konfrm-radius-card)] bg-[var(--konfrm-surface-secondary)] p-4"><p className="text-[16px] font-extrabold text-[var(--konfrm-text-primary)]">{cancellationConfirmModal.action === 'approve' ? 'هل تريد قبول طلب الإلغاء؟' : 'هل تريد رفض طلب الإلغاء؟'}</p></div>{cancellationConfirmModal.action === 'reject' && <label className="block text-[14px] font-bold text-[var(--konfrm-text-primary)]">سبب الرفض <span className="font-normal text-[var(--konfrm-text-secondary)]">(اختياري)</span><textarea rows={3} value={cancellationConfirmModal.reason} onChange={(event) => setCancellationConfirmModal((current) => ({ ...current, reason: event.target.value }))} className="mt-2 w-full rounded-[var(--konfrm-radius-control)] border border-[var(--konfrm-border-default)] bg-[var(--konfrm-surface-primary)] p-3 text-[14px] text-[var(--konfrm-text-primary)] outline-none focus:border-[var(--konfrm-border-focus)]" /></label>}{actionError && <p role="alert" className="rounded-[var(--konfrm-radius-control)] border border-rose-200 bg-rose-50 p-3 text-[14px] font-bold text-rose-800">{actionError}</p>}<div className="grid grid-cols-2 gap-3"><Button variant="outline" size="md" fullWidth disabled={isSubmitting} onClick={() => setCancellationConfirmModal(resetCancellationConfirm)}>إلغاء</Button><Button variant={cancellationConfirmModal.action === 'approve' ? 'primary' : 'danger'} size="md" fullWidth isLoading={isSubmitting} onClick={() => void executeCancellationAction()}>{cancellationConfirmModal.action === 'approve' ? 'تأكيد القبول' : 'تأكيد الرفض'}</Button></div></div></BottomSheet>
  </main>;
};
